Update plusbox.yml

diff --git a/.github/workflows/plusbox.yml b/.github/workflows/plusbox.yml
--- a/.github/workflows/plusbox.yml
+++ b/.github/workflows/plusbox.yml
@@ -2,8 +2,8 @@ name: Update Playlist
 
 on:
   schedule:
-    - cron: '0 * * * *' # প্রতি ১ ঘণ্টা পর পর রান হবে
-  workflow_dispatch: # যখন ইচ্ছা ম্যানুয়ালি রান করার জন্য
+    - cron: '0 * * * *'
+  workflow_dispatch:
 
 jobs:
   update-playlist:
@@ -35,10 +35,11 @@ jobs:
         run: |
           git config user.name "github-actions[bot]"
           git config user.email "github-actions[bot]@users.noreply.github.com"
-          git add playlist.m3u
+          # এই লাইনে পরিবর্তন করা হয়েছে যেন এরর না দেয়
+          git add playlist.m3u || echo "File not found"
           if git diff --cached --quiet; then
             echo "No changes to commit."
           else
-            git commit -m "chore: update playlist.m3u [$(date -u '+%Y-%m-%d %H:%M UTC')]"
+            git commit -m "chore: update playlist [$(date -u '+%Y-%m-%d %H:%M UTC')]"
             git push
           fi
